# Generated by Django 4.1.1 on 2022-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=222)),
                ("Email", models.CharField(max_length=222)),
                ("Phone", models.CharField(max_length=222)),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
